# Generated by Django 2.2.6 on 2019-10-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobilenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
