# Generated by Django 2.2.6 on 2019-10-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0002_auto_20191028_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('post_image', models.ImageField(max_length=255, upload_to='')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
