# Generated by Django 2.2.6 on 2019-10-29 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0003_userpostedimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostedimages',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 6, 15, 46, 455711)),
        ),
        migrations.AlterField(
            model_name='userpostedimages',
            name='post_image',
            field=models.ImageField(max_length=255, upload_to='uploaded_images/'),
        ),
    ]
