# Generated by Django 2.2.6 on 2019-10-29 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0004_auto_20191029_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostedimages',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
