# Generated by Django 2.2.6 on 2019-10-29 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0005_auto_20191029_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostedimages',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 6, 17, 32, 64517)),
        ),
    ]
