# Generated by Django 2.2.6 on 2019-10-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0007_auto_20191029_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostedimages',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
