# Generated by Django 2.2.6 on 2019-10-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0008_auto_20191029_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likecount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('like_count', models.IntegerField()),
                ('post_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signupform.UserPostedImages')),
            ],
        ),
    ]
