# Generated by Django 2.2.6 on 2019-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0009_likecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostedimages',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
