# Generated by Django 2.2.6 on 2019-10-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0010_userpostedimages_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecount',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
