# Generated by Django 2.2.6 on 2019-10-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0011_auto_20191029_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostedimages',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
